title = "R'tichoke"
theme = "axiom"
baseURL = "https://rtichoke.netlify.app/"
languageCode = "en-us"
defaultContentLanguage = "en"

paginate = 3
canonifyURLs = false
summaryLength = 10
rssLimit = 100
enableEmoji = true
enableRobotsTXT = true
pluralizelisttitles = false

[permalinks]
posts = "/:filename"

[params]
copyrightYear = 2020
dateFormat = "Jan 2, 2006"
maxWidthContent = "max-w-4xl"
maxWidthTitle = "max-w-4xl"

[menu]
[[menu.main]]
url = "/post/"
name = "Posts"
weight = 1

[[menu.main]]
url = "/about/"
name = "About"
weight = 1

[params.social]
github = "https://github.com/royr2"
linkedin = "https://www.linkedin.com/in/riddhimanr"
twitter = "https://twitter.com/r0yr2"
footer = ["twitter", "github", "linkedin"]

[params.services]
googleAnalyticsId = "UA-57026003-1"
disqusShortname = "rtichoke"
